name: CI

on:
  schedule:
    - cron: '14 15 25 * *'
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    container:
      image: practicalscheme/gauche
    steps:
      - uses: actions/checkout@v4
      - name: Setup package
        run: |
          apt-get update -y --allow-releaseinfo-change;
          apt-get install -y libidn11-dev;
      - name: CI
        run: ./run-ci.sh
